language: php

php:
  - '5.6'

cache:
    directories:
        - $HOME/.composer/cache

sudo: false

before_script:
    - composer selfupdate

install: composer install

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

